name: Generate ASCII Artwork

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        -   name: Chcekout repo
            uses: actions/checkout@v5
        
        -   name: List Repo Files
            run: ls -lrt

        -   name: Execute Shell script
            run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh